package com.woniu.pojo;
// Generated 2019-12-20 10:16:45 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Checkrecord generated by hbm2java
 */
public class Checkrecord implements java.io.Serializable {

	private Integer crid;
	private Checktype checktype;
	private Date crdate;
	private Set students = new HashSet(0);

	public Checkrecord() {
	}

	public Checkrecord(Checktype checktype, Date crdate, Set students) {
		this.checktype = checktype;
		this.crdate = crdate;
		this.students = students;
	}

	public Integer getCrid() {
		return this.crid;
	}

	public void setCrid(Integer crid) {
		this.crid = crid;
	}

	public Checktype getChecktype() {
		return this.checktype;
	}

	public void setChecktype(Checktype checktype) {
		this.checktype = checktype;
	}

	public Date getCrdate() {
		return this.crdate;
	}

	public void setCrdate(Date crdate) {
		this.crdate = crdate;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
