package com.woniu.pojo;
// Generated 2019-12-20 10:16:45 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Checktype generated by hbm2java
 */
public class Checktype implements java.io.Serializable {

	private Integer ctid;
	private String ctname;
	private Set checkrecords = new HashSet(0);

	public Checktype() {
	}

	public Checktype(String ctname, Set checkrecords) {
		this.ctname = ctname;
		this.checkrecords = checkrecords;
	}

	public Integer getCtid() {
		return this.ctid;
	}

	public void setCtid(Integer ctid) {
		this.ctid = ctid;
	}

	public String getCtname() {
		return this.ctname;
	}

	public void setCtname(String ctname) {
		this.ctname = ctname;
	}

	public Set getCheckrecords() {
		return this.checkrecords;
	}

	public void setCheckrecords(Set checkrecords) {
		this.checkrecords = checkrecords;
	}

}
