package com.woniu.pojo;
// Generated 2019-12-20 10:16:45 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	private Integer cid;
	private Headmaster headmaster;
	private Stage stage;
	private Supervisor supervisor;
	private Teacher teacher;
	private String cname;
	private String ctype;
	private Set students = new HashSet(0);

	public Classes() {
	}

	public Classes(Headmaster headmaster, Stage stage, Supervisor supervisor, Teacher teacher, String cname,
			String ctype, Set students) {
		this.headmaster = headmaster;
		this.stage = stage;
		this.supervisor = supervisor;
		this.teacher = teacher;
		this.cname = cname;
		this.ctype = ctype;
		this.students = students;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Headmaster getHeadmaster() {
		return this.headmaster;
	}

	public void setHeadmaster(Headmaster headmaster) {
		this.headmaster = headmaster;
	}

	public Stage getStage() {
		return this.stage;
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public Supervisor getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(Supervisor supervisor) {
		this.supervisor = supervisor;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getCtype() {
		return this.ctype;
	}

	public void setCtype(String ctype) {
		this.ctype = ctype;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
