package com.woniu.pojo;
// Generated 2019-12-19 14:36:06 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examrecord generated by hbm2java
 */
public class Examrecord implements java.io.Serializable {

	private Integer erid;
	private Classes classes;
	private Stage stage;
	private Student student;
	private String score;
	private Date erdate;
	private Set students = new HashSet(0);

	public Examrecord() {
	}

	public Examrecord(Classes classes, Stage stage, Student student, String score, Date erdate, Set students) {
		this.classes = classes;
		this.stage = stage;
		this.student = student;
		this.score = score;
		this.erdate = erdate;
		this.students = students;
	}

	public Integer getErid() {
		return this.erid;
	}

	public void setErid(Integer erid) {
		this.erid = erid;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public Stage getStage() {
		return this.stage;
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	public Date getErdate() {
		return this.erdate;
	}

	public void setErdate(Date erdate) {
		this.erdate = erdate;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
