package com.woniu.pojo;
// Generated 2019-12-20 10:16:45 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Stage generated by hbm2java
 */
public class Stage implements java.io.Serializable {

	private Integer sid;
	private String sname;
	private Set examrecords = new HashSet(0);
	private Set teachers = new HashSet(0);
	private Set headmasters = new HashSet(0);
	private Set classeses = new HashSet(0);
	private Set students = new HashSet(0);

	public Stage() {
	}

	public Stage(String sname, Set examrecords, Set teachers, Set headmasters, Set classeses, Set students) {
		this.sname = sname;
		this.examrecords = examrecords;
		this.teachers = teachers;
		this.headmasters = headmasters;
		this.classeses = classeses;
		this.students = students;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public Set getExamrecords() {
		return this.examrecords;
	}

	public void setExamrecords(Set examrecords) {
		this.examrecords = examrecords;
	}

	public Set getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set teachers) {
		this.teachers = teachers;
	}

	public Set getHeadmasters() {
		return this.headmasters;
	}

	public void setHeadmasters(Set headmasters) {
		this.headmasters = headmasters;
	}

	public Set getClasseses() {
		return this.classeses;
	}

	public void setClasseses(Set classeses) {
		this.classeses = classeses;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
