package com.woniu.pojo;
// Generated 2019-12-20 10:16:45 by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer stuid;
	private Checkrecord checkrecord;
	private Classes classes;
	private Examrecord examrecord;
	private Headmaster headmaster;
	private Stage stage;
	private Teacher teacher;
	private String stuname;
	private String sex;
	private String idcard;
	private Date intime;
	private String phone;
	private String address;
	private Date edutime;
	private String school;
	private String domain;

	public Student() {
	}

	public Student(String idcard) {
		this.idcard = idcard;
	}

	public Student(Checkrecord checkrecord, Classes classes, Examrecord examrecord, Headmaster headmaster, Stage stage,
			Teacher teacher, String stuname, String sex, String idcard, Date intime, String phone, String address,
			Date edutime, String school, String domain) {
		this.checkrecord = checkrecord;
		this.classes = classes;
		this.examrecord = examrecord;
		this.headmaster = headmaster;
		this.stage = stage;
		this.teacher = teacher;
		this.stuname = stuname;
		this.sex = sex;
		this.idcard = idcard;
		this.intime = intime;
		this.phone = phone;
		this.address = address;
		this.edutime = edutime;
		this.school = school;
		this.domain = domain;
	}

	public Integer getStuid() {
		return this.stuid;
	}

	public void setStuid(Integer stuid) {
		this.stuid = stuid;
	}

	public Checkrecord getCheckrecord() {
		return this.checkrecord;
	}

	public void setCheckrecord(Checkrecord checkrecord) {
		this.checkrecord = checkrecord;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public Examrecord getExamrecord() {
		return this.examrecord;
	}

	public void setExamrecord(Examrecord examrecord) {
		this.examrecord = examrecord;
	}

	public Headmaster getHeadmaster() {
		return this.headmaster;
	}

	public void setHeadmaster(Headmaster headmaster) {
		this.headmaster = headmaster;
	}

	public Stage getStage() {
		return this.stage;
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getStuname() {
		return this.stuname;
	}

	public void setStuname(String stuname) {
		this.stuname = stuname;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	public Date getIntime() {
		return this.intime;
	}

	public void setIntime(Date intime) {
		this.intime = intime;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getEdutime() {
		return this.edutime;
	}

	public void setEdutime(Date edutime) {
		this.edutime = edutime;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	
}
