package com.woniu.pojo;
// Generated 2019-12-20 10:16:45 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Supervisor generated by hbm2java
 */
public class Supervisor implements java.io.Serializable {

	private Integer supid;
	private String supname;
	private Set headmasters = new HashSet(0);
	private Set teachers = new HashSet(0);
	private Set classeses = new HashSet(0);

	public Supervisor() {
	}

	public Supervisor(String supname, Set headmasters, Set teachers, Set classeses) {
		this.supname = supname;
		this.headmasters = headmasters;
		this.teachers = teachers;
		this.classeses = classeses;
	}

	public Integer getSupid() {
		return this.supid;
	}

	public void setSupid(Integer supid) {
		this.supid = supid;
	}

	public String getSupname() {
		return this.supname;
	}

	public void setSupname(String supname) {
		this.supname = supname;
	}

	public Set getHeadmasters() {
		return this.headmasters;
	}

	public void setHeadmasters(Set headmasters) {
		this.headmasters = headmasters;
	}

	public Set getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set teachers) {
		this.teachers = teachers;
	}

	public Set getClasseses() {
		return this.classeses;
	}

	public void setClasseses(Set classeses) {
		this.classeses = classeses;
	}

}
