package com.woniu.pojo;
// Generated 2019-12-20 10:16:45 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer tid;
	private Stage stage;
	private Supervisor supervisor;
	private String tname;
	private Set students = new HashSet(0);
	private Set classeses = new HashSet(0);

	public Teacher() {
	}

	public Teacher(Stage stage, Supervisor supervisor, String tname, Set students, Set classeses) {
		this.stage = stage;
		this.supervisor = supervisor;
		this.tname = tname;
		this.students = students;
		this.classeses = classeses;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public Stage getStage() {
		return this.stage;
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public Supervisor getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(Supervisor supervisor) {
		this.supervisor = supervisor;
	}

	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

	public Set getClasseses() {
		return this.classeses;
	}

	public void setClasseses(Set classeses) {
		this.classeses = classeses;
	}

}
